#!/bin/bash

OPERATION=$1
shift
ARGS=$*

export UID

case ${OPERATION} in
    "build") docker-compose run --rm node node_modules/.bin/webpack ui/src/index.js html/js/app.js;;
    "cli") docker-compose run --rm php-cli php ${ARGS};;
    "composer") docker-compose run --rm composer ${ARGS};;
    "npm") docker-compose run --rm node npm ${ARGS};;
    *) echo "Unknown operation: ${OPERATION}";;
esac