version: '3.4'
volumes: {  }
services:
    httpd: { build: ./docker/httpd, ports: ['8080:80'], volumes: ['./:/var/www/'] }
    php-cli: { build: ./docker/php/, working_dir: /var/www/, volumes: ['./:/var/www/'] }
    composer: { image: composer, volumes: ['./:/var/www/', '~/.ssh/:/root/.ssh'], tty: true, working_dir: /var/www/, command: 'composer install' }
    nodejs: { image: 'node:9.10', working_dir: /var/www/, volumes: ['./:/data'] }
    php-unit-tests: { build: ./docker/php/, working_dir: /var/www/, volumes: ['./:/var/www/'], command: 'vendor/bin/phpunit' }