#!/bin/bash

OPERATION=$1
shift
ARGS=$*

case ${OPERATION} in
    "cli") docker-compose run --rm php-cli php ${ARGS};;
    "composer") docker-compose run --rm composer ${ARGS};;
    *) echo "Unknown operation: ${OPERATION}";;
esac